version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: silky_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"
    networks:
      - silky_network

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: silky_fastapi
    depends_on:
      - mysql
    env_file:
      - .env
    working_dir: /app
    command: >
      bash -c "
      python check_db_connection.py &&
      alembic -c alembic.ini upgrade head &&
      uvicorn backend.main:app --host 0.0.0.0 --port 8000
      "
    ports:
      - "8000:8000"
    restart: always
    networks:
      - silky_network

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: silky_bot
    restart: always
    depends_on:
      - fastapi
    env_file:
      - .env
    working_dir: /app
    command: [ "python", "bot/bot.py" ]
    networks:
      - silky_network

volumes:
  mysql_data:

networks:
  silky_network:
    driver: bridge
