services:
  mysql:
    image: mysql:8.0
    container_name: silky_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: silky_fastapi
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: nurtas
      DB_PASS: nurtas05
      DB_NAME: products_db
    working_dir: /app/backend
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: silky_bot
    restart: unless-stopped
    depends_on:
      - fastapi
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      API_URL: http://fastapi:8000
    working_dir: /app
    command: [ "python", "bot/bot.py" ]
    dns:
      - 8.8.8.8

volumes:
  mysql_data:
